Universe           = vanilla
Initialdir         = control_file_to_be_updated/condor_outputs
Executable         = control_file_to_be_updated/run_root_sub_the_file_number.sh
PeriodicHold       = (NumJobStarts>=1 && JobStatus == 1)
request_memory     = 4GB
Priority           = 20
job_lease_duration = 86400
nEvents            = NEVENTS
InputfilelistIdx   = INPUTFILELISTIDX
FileName           = FILENAME
skipEvt            = 0
Output             = condor_output_to_be_updated/CW_log/condor_the_file_number.out
Error              = condor_output_to_be_updated/CW_log/condor_the_file_number.err
Log                = condor_output_to_be_updated/CW_log/condor_the_file_number.log
Arguments          = "$(nEvents) $(InputfilelistIdx) $(FileName) $(skipEvt)"
Queue 1

